### PR TITLE
Show Chuck Norris quotes

### PR DESCRIPTION
**Pull request by faergeek**
This app doesn't make sense if we can't [get Chuck Norris' quotes from protected and trusted source](https://github.com/auth0/nodejs-jwt-authentication-sample#get-apiprotectedrandom-quote)

### CODE REVIEW

**Comment by mgonto** [comment]
Looks great :).

Can you rebase and I'll merge it then :)?

Thanks!

**Comment by faergeek** [comment]
Done! :)

**Comment by mgonto** [comment]
Awesome :).

Merging!

Thanksss!!

**Comment by faergeek** [comment]
You're welcome!

Great post, BTW.

**Comment by mgonto** [comment]
Thanks :). Glad you liked the post :).

**Pull request merged**
