### PR TITLE
this one fixes typo :)

### PR DESCRIPTION
**Pull request by olegakbarov**
yeah!

### CODE REVIEW

**Comment by mgonto** [comment]
Thanks! Can you rebase and I'll merge!

**Comment by olegakbarov** [comment]
it took time, sorry

**Comment by mgonto** [comment]
Thanks :)

Merging now!

Thanks for helping!

**Comment by olegakbarov** [comment]
Thanks for great tut, it was very helpful :+1:

**Comment by mgonto** [comment]
I'm glad it was helpful :).

Cheers!

**Pull request merged**
